server:
  port: 8764
spring:
  application:
    name: User-Service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/asset_tracking_system
    username: root
    password: Falcon2025adam1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: N5WhWwSLgEQJwQl/GUJEWXwwtY4yPrMhEg9M00jRGvgYyC5X137sXxbVp3bZgJd9EkLQ18rkIwkVZU7XhPJ7SA==
  expiration: 3600000